project:
  type: onlimit-theme

website:
  title: "ON LiMiT"
  site-url: "https://onlimit.dk/"
  repo-url: "https://github.com/on-limit-study/main-website"
  navbar:
    pinned: true
    left:
      - text: "Menu"
        menu:
          - text: "Om ON LiMiT"
            href: about.md
          - text: "For praktiserende læger"
            href: practitioners.md
          - text: "For deltagere i pilotstudiet"
            href: participants_feasibility.md
          - text: "For forskere"
            href: researchers.md
    tools:
      - icon: github
        href: "https://onlimit.dk"
        aria-label: "GitHub icon: Link to ON LiMIT GitHub Organization page"


format:
  onlimit-theme-html:
    theme:
      - onlimit-theme-html
      - style.scss

editor:
  markdown:
    wrap: 72
    canonical: true
